---
api_host: screeps.com
api_prefix: ''
api_token: ${SCREEPS_AUTH_TOKEN}
api_username: ''
api_password: ''
api_secure: true

target_shard: shard1
target_players:
- admon

spy_rcl: true
spy_resources: true
spy_rooms:
- W6S9
spy_structures:
- storage
- terminal
- factory
- lab
spy_market: false

results_output: true

results_save_file: false
results_filename: spybot_results.json

results_memory: false
results_memory_path: Memory.spybot

results_segment: false
results_segment_target: 99