---
api_host: screeps.com
api_prefix: '/season'
api_token: ${SCREEPS_AUTH_TOKEN}

target_shard: shardSeason
target_players:
- likeafox

spy_rcl: true
spy_resources: false
spy_structures:
- storage
- terminal
- factory
- lab
spy_market: false

results_output: true

results_save_file: false
results_filename: warbot_data.json

results_memory: false
results_memory_path: Memory.warbot

results_segment: true
results_segment_target: 99